# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlterInfo.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlterInfo(object):
    def setupUi(self, AlterInfo):
        AlterInfo.setObjectName("AlterInfo")
        AlterInfo.resize(400, 500)
        self.label_3 = QtWidgets.QLabel(AlterInfo)
        self.label_3.setGeometry(QtCore.QRect(45, 130, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AlterInfo)
        self.label_4.setGeometry(QtCore.QRect(45, 190, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(AlterInfo)
        self.label_5.setGeometry(QtCore.QRect(45, 250, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AlterInfo)
        self.label_6.setGeometry(QtCore.QRect(45, 310, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(AlterInfo)
        self.line.setGeometry(QtCore.QRect(0, 60, 400, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(AlterInfo)
        self.label.setGeometry(QtCore.QRect(140, 15, 120, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_tel = QtWidgets.QLineEdit(AlterInfo)
        self.lineEdit_tel.setGeometry(QtCore.QRect(150, 130, 200, 31))
        self.lineEdit_tel.setObjectName("lineEdit_tel")
        self.lineEdit_email = QtWidgets.QLineEdit(AlterInfo)
        self.lineEdit_email.setGeometry(QtCore.QRect(150, 190, 200, 31))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_oldpw = QtWidgets.QLineEdit(AlterInfo)
        self.lineEdit_oldpw.setGeometry(QtCore.QRect(150, 250, 200, 31))
        self.lineEdit_oldpw.setObjectName("lineEdit_oldpw")
        self.lineEdit_newpw = QtWidgets.QLineEdit(AlterInfo)
        self.lineEdit_newpw.setGeometry(QtCore.QRect(150, 310, 200, 31))
        self.lineEdit_newpw.setObjectName("lineEdit_newpw")
        self.buttonBox = QtWidgets.QDialogButtonBox(AlterInfo)
        self.buttonBox.setGeometry(QtCore.QRect(100, 405, 200, 33))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(AlterInfo)
        QtCore.QMetaObject.connectSlotsByName(AlterInfo)

    def retranslateUi(self, AlterInfo):
        _translate = QtCore.QCoreApplication.translate
        AlterInfo.setWindowTitle(_translate("AlterInfo", "Form"))
        self.label_3.setText(_translate("AlterInfo", "手机号码"))
        self.label_4.setText(_translate("AlterInfo", "email"))
        self.label_5.setText(_translate("AlterInfo", "原密码"))
        self.label_6.setText(_translate("AlterInfo", "新密码"))
        self.label.setText(_translate("AlterInfo", "信息修改"))
