# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomePage.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 720)
        Form.setStyleSheet("background-color: rgb(228, 228, 228);")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 960, 54))
        self.frame.setStyleSheet("background-color: rgb(166, 200, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_homepage = QtWidgets.QPushButton(self.frame)
        self.pushButton_homepage.setGeometry(QtCore.QRect(830, 2, 130, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_homepage.setFont(font)
        self.pushButton_homepage.setStyleSheet("border:2px outset rgb(102, 102, 102);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(129, 155, 198);")
        self.pushButton_homepage.setFlat(False)
        self.pushButton_homepage.setObjectName("pushButton_homepage")
        self.pushButton_newpost = QtWidgets.QPushButton(self.frame)
        self.pushButton_newpost.setGeometry(QtCore.QRect(570, 2, 130, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_newpost.setFont(font)
        self.pushButton_newpost.setStyleSheet("border:2px outset rgb(102, 102, 102);\n"
"background-color: rgb(166, 200, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_newpost.setCheckable(False)
        self.pushButton_newpost.setAutoDefault(True)
        self.pushButton_newpost.setDefault(True)
        self.pushButton_newpost.setFlat(False)
        self.pushButton_newpost.setObjectName("pushButton_newpost")
        self.pushButton_msgcenter = QtWidgets.QPushButton(self.frame)
        self.pushButton_msgcenter.setGeometry(QtCore.QRect(700, 2, 130, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_msgcenter.setFont(font)
        self.pushButton_msgcenter.setStyleSheet("border:2px outset rgb(102, 102, 102);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(166, 200, 255);")
        self.pushButton_msgcenter.setFlat(False)
        self.pushButton_msgcenter.setObjectName("pushButton_msgcenter")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 2, 108, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(30, 5, 50, 50))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prefix/images/post_symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(40, 90, 880, 590))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(580, 140, 150, 150))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/prefix/images/head.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 350, 130, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(129, 155, 198);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(120, 130, 121, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(120, 200, 121, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(120, 270, 121, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(120, 340, 121, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(120, 410, 121, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_id = QtWidgets.QLabel(self.frame_2)
        self.label_id.setGeometry(QtCore.QRect(260, 130, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.label_role = QtWidgets.QLabel(self.frame_2)
        self.label_role.setGeometry(QtCore.QRect(260, 200, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_role.setFont(font)
        self.label_role.setObjectName("label_role")
        self.label_tel = QtWidgets.QLabel(self.frame_2)
        self.label_tel.setGeometry(QtCore.QRect(260, 270, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_tel.setFont(font)
        self.label_tel.setObjectName("label_tel")
        self.label_email = QtWidgets.QLabel(self.frame_2)
        self.label_email.setGeometry(QtCore.QRect(260, 340, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.label_money = QtWidgets.QLabel(self.frame_2)
        self.label_money.setGeometry(QtCore.QRect(260, 410, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_money.setFont(font)
        self.label_money.setObjectName("label_money")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_homepage.setText(_translate("Form", "个人主页"))
        self.pushButton_newpost.setText(_translate("Form", "新帖列表"))
        self.pushButton_msgcenter.setText(_translate("Form", "消息中心"))
        self.label.setText(_translate("Form", "发新帖"))
        self.pushButton_2.setText(_translate("Form", "信息修改"))
        self.label_3.setText(_translate("Form", "账   号"))
        self.label_4.setText(_translate("Form", "平台角色"))
        self.label_5.setText(_translate("Form", "手机号码"))
        self.label_6.setText(_translate("Form", "email"))
        self.label_7.setText(_translate("Form", "财富值"))
        self.label_id.setText(_translate("Form", "TextLabel"))
        self.label_role.setText(_translate("Form", "TextLabel"))
        self.label_tel.setText(_translate("Form", "TextLabel"))
        self.label_email.setText(_translate("Form", "TextLabel"))
        self.label_money.setText(_translate("Form", "TextLabel"))
import image_rc
