# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Msgcenter.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Msgcenter(object):
    def setupUi(self, Msgcenter):
        Msgcenter.setObjectName("Msgcenter")
        Msgcenter.resize(960, 720)
        Msgcenter.setStyleSheet("background-color: rgb(228, 228, 228);")
        self.frame = QtWidgets.QFrame(Msgcenter)
        self.frame.setGeometry(QtCore.QRect(0, 0, 960, 54))
        self.frame.setStyleSheet("background-color: rgb(166, 200, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_homepage = QtWidgets.QPushButton(self.frame)
        self.pushButton_homepage.setGeometry(QtCore.QRect(830, 2, 130, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_homepage.setFont(font)
        self.pushButton_homepage.setStyleSheet("border:2px outset rgb(102, 102, 102);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(166, 200, 255);")
        self.pushButton_homepage.setFlat(False)
        self.pushButton_homepage.setObjectName("pushButton_homepage")
        self.pushButton_newpost = QtWidgets.QPushButton(self.frame)
        self.pushButton_newpost.setGeometry(QtCore.QRect(570, 2, 130, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_newpost.setFont(font)
        self.pushButton_newpost.setStyleSheet("border:2px outset rgb(102, 102, 102);\n"
"background-color: rgb(166, 200, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_newpost.setCheckable(False)
        self.pushButton_newpost.setAutoDefault(True)
        self.pushButton_newpost.setDefault(True)
        self.pushButton_newpost.setFlat(False)
        self.pushButton_newpost.setObjectName("pushButton_newpost")
        self.pushButton_msgcenter = QtWidgets.QPushButton(self.frame)
        self.pushButton_msgcenter.setGeometry(QtCore.QRect(700, 2, 130, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_msgcenter.setFont(font)
        self.pushButton_msgcenter.setStyleSheet("border:2px outset rgb(102, 102, 102);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(129, 155, 198);")
        self.pushButton_msgcenter.setFlat(False)
        self.pushButton_msgcenter.setObjectName("pushButton_msgcenter")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 2, 108, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(30, 5, 50, 50))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/prefix/images/post_symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(Msgcenter)
        self.tabWidget.setGeometry(QtCore.QRect(40, 90, 870, 590))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(30, 105, 770, 16))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(30, 210, 770, 16))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(30, 315, 770, 16))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(30, 420, 770, 16))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.chat_history_1 = QtWidgets.QLabel(self.tab)
        self.chat_history_1.setGeometry(QtCore.QRect(320, 45, 400, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.chat_history_1.setFont(font)
        self.chat_history_1.setObjectName("chat_history_1")
        self.chat_history_2 = QtWidgets.QLabel(self.tab)
        self.chat_history_2.setGeometry(QtCore.QRect(320, 145, 400, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.chat_history_2.setFont(font)
        self.chat_history_2.setObjectName("chat_history_2")
        self.chat_history_3 = QtWidgets.QLabel(self.tab)
        self.chat_history_3.setGeometry(QtCore.QRect(320, 255, 400, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.chat_history_3.setFont(font)
        self.chat_history_3.setObjectName("chat_history_3")
        self.chat_history_4 = QtWidgets.QLabel(self.tab)
        self.chat_history_4.setGeometry(QtCore.QRect(320, 360, 400, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.chat_history_4.setFont(font)
        self.chat_history_4.setObjectName("chat_history_4")
        self.chat_history_5 = QtWidgets.QLabel(self.tab)
        self.chat_history_5.setGeometry(QtCore.QRect(320, 465, 400, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.chat_history_5.setFont(font)
        self.chat_history_5.setObjectName("chat_history_5")
        self.chat_user_id_1 = QtWidgets.QPushButton(self.tab)
        self.chat_user_id_1.setGeometry(QtCore.QRect(50, 45, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.chat_user_id_1.setFont(font)
        self.chat_user_id_1.setFlat(True)
        self.chat_user_id_1.setObjectName("chat_user_id_1")
        self.chat_user_id_2 = QtWidgets.QPushButton(self.tab)
        self.chat_user_id_2.setGeometry(QtCore.QRect(50, 145, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.chat_user_id_2.setFont(font)
        self.chat_user_id_2.setFlat(True)
        self.chat_user_id_2.setObjectName("chat_user_id_2")
        self.chat_user_id_3 = QtWidgets.QPushButton(self.tab)
        self.chat_user_id_3.setGeometry(QtCore.QRect(50, 255, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.chat_user_id_3.setFont(font)
        self.chat_user_id_3.setFlat(True)
        self.chat_user_id_3.setObjectName("chat_user_id_3")
        self.chat_user_id_4 = QtWidgets.QPushButton(self.tab)
        self.chat_user_id_4.setGeometry(QtCore.QRect(50, 360, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.chat_user_id_4.setFont(font)
        self.chat_user_id_4.setFlat(True)
        self.chat_user_id_4.setObjectName("chat_user_id_4")
        self.chat_user_id_5 = QtWidgets.QPushButton(self.tab)
        self.chat_user_id_5.setGeometry(QtCore.QRect(50, 465, 200, 40))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.chat_user_id_5.setFont(font)
        self.chat_user_id_5.setFlat(True)
        self.chat_user_id_5.setObjectName("chat_user_id_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line_5 = QtWidgets.QFrame(self.tab_2)
        self.line_5.setGeometry(QtCore.QRect(30, 420, 770, 16))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setGeometry(QtCore.QRect(30, 105, 770, 16))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_6.setFont(font)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setGeometry(QtCore.QRect(30, 315, 770, 16))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setGeometry(QtCore.QRect(30, 210, 770, 16))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.sys_msg_1 = QtWidgets.QLabel(self.tab_2)
        self.sys_msg_1.setGeometry(QtCore.QRect(80, 25, 650, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.sys_msg_1.setFont(font)
        self.sys_msg_1.setObjectName("sys_msg_1")
        self.sys_msg_2 = QtWidgets.QLabel(self.tab_2)
        self.sys_msg_2.setGeometry(QtCore.QRect(80, 130, 650, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.sys_msg_2.setFont(font)
        self.sys_msg_2.setObjectName("sys_msg_2")
        self.sys_msg_3 = QtWidgets.QLabel(self.tab_2)
        self.sys_msg_3.setGeometry(QtCore.QRect(80, 235, 650, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.sys_msg_3.setFont(font)
        self.sys_msg_3.setObjectName("sys_msg_3")
        self.sys_msg_4 = QtWidgets.QLabel(self.tab_2)
        self.sys_msg_4.setGeometry(QtCore.QRect(80, 340, 650, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.sys_msg_4.setFont(font)
        self.sys_msg_4.setObjectName("sys_msg_4")
        self.sys_msg_5 = QtWidgets.QLabel(self.tab_2)
        self.sys_msg_5.setGeometry(QtCore.QRect(80, 445, 650, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.sys_msg_5.setFont(font)
        self.sys_msg_5.setObjectName("sys_msg_5")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Msgcenter)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Msgcenter)

    def retranslateUi(self, Msgcenter):
        _translate = QtCore.QCoreApplication.translate
        Msgcenter.setWindowTitle(_translate("Msgcenter", "Form"))
        self.pushButton_homepage.setText(_translate("Msgcenter", "个人主页"))
        self.pushButton_newpost.setText(_translate("Msgcenter", "新帖列表"))
        self.pushButton_msgcenter.setText(_translate("Msgcenter", "消息中心"))
        self.label.setText(_translate("Msgcenter", "发新帖"))
        self.chat_history_1.setText(_translate("Msgcenter", "TextLabel"))
        self.chat_history_2.setText(_translate("Msgcenter", "TextLabel"))
        self.chat_history_3.setText(_translate("Msgcenter", "TextLabel"))
        self.chat_history_4.setText(_translate("Msgcenter", "TextLabel"))
        self.chat_history_5.setText(_translate("Msgcenter", "TextLabel"))
        self.chat_user_id_1.setText(_translate("Msgcenter", "PushButton"))
        self.chat_user_id_2.setText(_translate("Msgcenter", "PushButton"))
        self.chat_user_id_3.setText(_translate("Msgcenter", "PushButton"))
        self.chat_user_id_4.setText(_translate("Msgcenter", "PushButton"))
        self.chat_user_id_5.setText(_translate("Msgcenter", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Msgcenter", "我的私信"))
        self.sys_msg_1.setText(_translate("Msgcenter", "TextLabel"))
        self.sys_msg_2.setText(_translate("Msgcenter", "TextLabel"))
        self.sys_msg_3.setText(_translate("Msgcenter", "TextLabel"))
        self.sys_msg_4.setText(_translate("Msgcenter", "TextLabel"))
        self.sys_msg_5.setText(_translate("Msgcenter", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Msgcenter", "系统消息"))
import image_rc
