-- MySQL Script generated by MySQL Workbench
-- Mon Nov  1 10:59:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` VARCHAR(20) NOT NULL,
  `tel` VARCHAR(20) NULL,
  `birthday` DATE NULL,
  `sex` ENUM('man', 'woman') NULL,
  `email` VARCHAR(40) NULL,
  `money` INT NULL,
  `user_role` ENUM('user', 'admin') NULL,
  `deleted_num` INT NULL,
  `user_pw` VARCHAR(25) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `posted_time` TIMESTAMP NOT NULL,
  `content` LONGTEXT NOT NULL,
  `accept_status` ENUM('accepted', 'not_accepted') NOT NULL,
  `accepter_user_id` VARCHAR(20) NOT NULL,
  `visible_en` ENUM('y', 'n') NOT NULL COMMENT 'If a post is deleted, then it is invisible.',
  `poster_user_id` VARCHAR(20) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `user_id_idx` (`accepter_user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`accepter_user_id` ASC) VISIBLE,
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC) VISIBLE,
  UNIQUE INDEX `poster_user_id_UNIQUE` (`poster_user_id` ASC) VISIBLE,
  CONSTRAINT `poster_user_id`
    FOREIGN KEY (`accepter_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `accepter_user_id`
    FOREIGN KEY (`accepter_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chat_history` (
  `inq_id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` VARCHAR(20) NOT NULL,
  `receiver_id` VARCHAR(20) NOT NULL,
  `send_time` TIMESTAMP NOT NULL,
  `sender_role` ENUM('user', 'admin') NOT NULL,
  `msg_type` ENUM('text') NOT NULL,
  `msg_body` TEXT(200) NOT NULL,
  PRIMARY KEY (`inq_id`),
  UNIQUE INDEX `chat_history_id_UNIQUE` (`inq_id` ASC) VISIBLE,
  INDEX `receiver_id_idx` (`receiver_id` ASC) VISIBLE,
  CONSTRAINT `sender_id`
    FOREIGN KEY (`sender_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `receiver_id`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
